In [8]:
import numpy as np



# The McEliece Cryptosystem

## SETUP:
- Let C be an (n,k)-linear code with a fast decoding algorithm that can correct t errors. 
- Let G be a generator matrix for C. 
- Let S be a k × k invertible matrix (the scrambler)
- Let P be an n × n permutation matrix
- The matrix, PK = SGP is made public (pubkey) while S, G and P are kept secret by Bob. 



In [23]:
n = 7
k = 4
G = np.array([[1,0,0,0,1,1,0],[0,1,0,0,1,0,1],[0,0,1,0,0,1,1],[0,0,0,1,1,1,1]])
S = np.array([[1,1,0,1],[1,0,0,1],[0,1,1,1],[1,1,0,0]])
P = np.array([[0,1,0,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,0,0,1],[1,0,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,0,0,1,0],[0,0,0,0,1,0,0]])
PK = np.mod(np.matmul(np.matmul(S, G), P), 2)
print("PublicKey:\n", PK)

PublicKey:
 [[1 1 1 1 0 0 0]
 [1 1 0 0 1 0 0]
 [1 0 0 1 1 0 1]
 [0 1 0 1 1 1 0]]


In [3]:
# For Alice to send a message to Bob, she blocks her message into binary vectors of length k.
#  If x is one such block, she randomly constructs a binary n-vector of weight t,
#  call it e and then sends to Bob the vector y = xG' + e.